use_frameworks!

platform :ios, '9.0'

target 'CPersonPrefrenceKit_Example' do
  pod 'CPersonPrefrenceKit', :path => '../'

  target 'CPersonPrefrenceKit_Tests' do
    inherit! :search_paths

    
  end
end
